### ISSUE TITLE
希望增加多支付功能

### ISSUE THREAD

**Issue by xsidc** [xcode75/XManager#1]
希望能想V2B那样，允许多个支付接口同时使用。

**Comment by xcode75** [comment]
> 希望能想V2B那样，允许多个支付接口同时使用。

已经支持多个接口， 你想用哪一个支付接口？

**Comment by xcode75** [comment]
> > 希望能想V2B那样，允许多个支付接口同时使用。
> 
> 已经支持多个接口， 你想用哪一个支付接口？

![image](https://user-images.githubusercontent.com/87862554/141281398-05670f54-bd3d-4633-8564-2d88418666b3.png)

**Comment by xsidc** [comment]
我的意思是，能同时使用。不是只对接1个。
![image](https://user-images.githubusercontent.com/55003092/141281412-e705c40b-7eb6-42df-a704-c5afe7bef9b0.png)

**Comment by xsidc** [comment]
![image](https://user-images.githubusercontent.com/55003092/141281508-3d608b40-70bf-4987-84fa-547ab28df3a0.png)
这里我只看到只能填写1个支付方式

**Comment by xcode75** [comment]
> ![image](https://user-images.githubusercontent.com/55003092/141281508-3d608b40-70bf-4987-84fa-547ab28df3a0.png) 这里我只看到只能填写1个支付方式

不对

**Comment by xcode75** [comment]
都支付接口可以启用

**Comment by xcode75** [comment]
你先看看吧

**Comment by xsidc** [comment]
我明白了，你这个做的不明显，我以为是保存只能保存1个。没想到你这个是可以保存多个。

**Comment by xsidc** [comment]
客户端有吗？

**Comment by xcode75** [comment]
> 客户端有吗？

现在没有

**Comment by xsidc** [comment]
好的，有了我要买
